CXX = g++
CXXFLAGS = -std=c++11 -O2 -Wall
INCLUDES = -I. -Ithird_party/butteraugli

butteraugli_diffmap_analysis: butteraugli_diffmap_analysis.cc third_party/butteraugli/butteraugli/butteraugli.cc
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ $^

clean:
	rm -f butteraugli_diffmap_analysis

.PHONY: clean